language: node_js
node_js:
- '5.8'
env:
  matrix:
  - CXX=g++-4.8
  global:
  - secure: h+zTK5t97Qv/okuEcRaWKnuAg3bdUcmPcnN8Am9h0L5gULcUs8a9oCFC5Z2Fxx8V43BZzmkzChsadgIGm6sjUjNREr87HI5o3zV7i1qEgl4tTmkEH4YrVxVUOTafbPJ1LD1+O9Bu+I/pap10Lv3+/bLAr+bye706M+kJBCH4uJY=
  - secure: hW8m/FFA4H6P8xYEmtE5d29qGJfeMAuh7B2UK6Whhyt8B2wv2UG8G5aXOcYsdSd5v0n+sapZFVzMmiTIayJBpBlSxlv3YXSO7be5h7bQheoMOmiHOImrFqgTaoNBFFhaV9v7iXdRhxsmz6axTHTu9AJknaow3jojNzqUamkyMpM=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
script:
- npm run build
after_success:
- gulp deploy --user $FTP_USER --password $FTP_PASSWORD
